# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UpdateLightCommand.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
  name='UpdateLightCommand.proto',
  package='proto.messages',
  serialized_pb=b'\n\x18UpdateLightCommand.proto\x12\x0eproto.messages\"\x80\x01\n\x12UpdateLightCommand\x12\x13\n\x0bmsg_version\x18\x01 \x02(\x05\x12\x10\n\x08light_id\x18\x02 \x02(\t\x12\x0f\n\x07rgb_red\x18\x03 \x02(\x05\x12\x11\n\trgb_green\x18\x04 \x02(\x05\x12\x10\n\x08rgb_blue\x18\x05 \x02(\x05\x12\r\n\x05is_on\x18\x06 \x02(\x08'
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_UPDATELIGHTCOMMAND = _descriptor.Descriptor(
  name='UpdateLightCommand',
  full_name='proto.messages.UpdateLightCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg_version', full_name='proto.messages.UpdateLightCommand.msg_version', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='light_id', full_name='proto.messages.UpdateLightCommand.light_id', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rgb_red', full_name='proto.messages.UpdateLightCommand.rgb_red', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rgb_green', full_name='proto.messages.UpdateLightCommand.rgb_green', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rgb_blue', full_name='proto.messages.UpdateLightCommand.rgb_blue', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_on', full_name='proto.messages.UpdateLightCommand.is_on', index=5,
      number=6, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,

  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=173,
)

DESCRIPTOR.message_types_by_name['UpdateLightCommand'] = _UPDATELIGHTCOMMAND

UpdateLightCommand = _reflection.GeneratedProtocolMessageType('UpdateLightCommand', (_message.Message,), dict(
  DESCRIPTOR = _UPDATELIGHTCOMMAND,
  __module__ = 'UpdateLightCommand_pb2'
  # @@protoc_insertion_point(class_scope:proto.messages.UpdateLightCommand)
  ))
_sym_db.RegisterMessage(UpdateLightCommand)


# @@protoc_insertion_point(module_scope)
